name: Telegram Backup Bot

on:
  schedule:
    - cron: '0 9 * * *'  # اجهر روز ساعت ۳ صبح UTC
  workflow_dispatch:

jobs:
  run-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run backup script
        env:
          TELEGRAM_BOT_TOKEN: 7255674500:AAHw1lN7oheFvZ3W-12MpGxkdzfbJ2pWsfM
          CHAT_ID: -1002795263743
        run: python backup_to_telegram.py
